// This file is automatically generated by i18next-cli. Do not edit manually.
import type Resources from './resources.ts'

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation'
    enableSelector: true
    resources: Resources
  }
}
